CREATE DATABASE wildlife_tracker;

\c Wildlife_tracker;

CREATE TABLE animals(
      id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR,
      type VARCHAR,
      age VARCHAR,
      health VARCHAR

);
CREATE TABLE sightings(
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     animalName VARCHAR,
    location VARCHAR,
    rangerName VARCHAR,
    Timestamp timestamp
);

CREATE DATABASE wildlife_tracker WITH TEMPLATE wildlife_tracker_test;
