CREATE DATABASE animals;

\c animals;

CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR,
      age INT,
      ranger VARCHAR,
      location VARCHAR,
      health INT,
      status VARCHAR,
      spottime timestamp
);

CREATE DATABASE animals_test WITH TEMPLATE animals;
