CREATE DATABASE wildlife_tracker;

\c Wildlife_tracker;

CREATE TABLE animals(
      animal_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR,
      ANIMAL_TYPE VARCHAR,
      age INT,
      health INT

);
CREATE TABLE sightings(
    animal_id int,
    location VARCHAR,
    rangerName VARCHAR,
    Timestamp timestamp
);

CREATE DATABASE wildlife_tracker WITH TEMPLATE wildlife_tracker_test;
